import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavBar from "@/components/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="fetch" href="/models/ferrari.glb" crossOrigin="anonymous" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/px.jpg" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/nx.jpg" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/py.jpg" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/ny.jpg" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/pz.jpg" />
        <link rel="preload" as="image" href="/textures/cube/skyboxsun25deg/nz.jpg" />
        <link rel="preload" as="image" href="/models/ferrari_ao.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
