export type ShopPost = {
  id: string;
  slug: string;
  title: string;
  description: string;
  price: number;
  priceNegotiable: boolean;
  category: string;
  subcategory: string;
  images: string[];
  city: string;
  university: string;
  userName: string;
  sellerRating: number;
  reviewCount: number;
  createdAt: string;
  type?: "buy" | "rent" | "both";
  colors?: string[];
  inventory?: number;
};

export const samplePosts: ShopPost[] = [
  {
    id: "1",
    slug: "sf90-xx",
    title: "SF90 XX Stradale",
    description: "Track-focused plug-in hybrid with extreme aero.",
    price: 850000,
    priceNegotiable: false,
    category: "limited",
    subcategory: "Hypercar",
    images: ["/carousel1.jpg"],
    city: "Maranello",
    university: "Ferrari Factory",
    userName: "Admin",
    sellerRating: 4.9,
    reviewCount: 128,
    createdAt: "2024-11-10",
    type: "both",
    colors: ["Rosso Corsa", "Giallo Modena", "Nero"],
    inventory: 2,
  },
  {
    id: "2",
    slug: "296-gtb",
    title: "296 GTB",
    description: "V6 hybrid berlinetta with astonishing balance.",
    price: 380000,
    priceNegotiable: true,
    category: "sports",
    subcategory: "GT",
    images: ["/carousel2.jpg"],
    city: "Modena",
    university: "UNIMORE",
    userName: "Dealer",
    sellerRating: 4.7,
    reviewCount: 86,
    createdAt: "2024-10-02",
    type: "both",
    colors: ["Rosso Corsa", "Blu Tour de France", "Argento Nürburgring"],
    inventory: 4,
  },
  {
    id: "3",
    slug: "roma-spider",
    title: "Roma Spider",
    description: "Open-top elegance with twin-turbo V8.",
    price: 320000,
    priceNegotiable: true,
    category: "luxury",
    subcategory: "Coupe",
    images: ["/carousel3.webp"],
    city: "Rome",
    university: "Sapienza",
    userName: "Showroom",
    sellerRating: 4.8,
    reviewCount: 54,
    createdAt: "2024-09-18",
    type: "rent",
    colors: ["Rosso Corsa", "Grigio Silverstone"],
    inventory: 3,
  },
  {
    id: "4",
    slug: "812-gts",
    title: "812 GTS",
    description: "Naturally aspirated V12 grand tourer.",
    price: 450000,
    priceNegotiable: false,
    category: "sports",
    subcategory: "GT",
    images: ["/carousel5.jpg"],
    city: "Monaco",
    university: "IUM",
    userName: "Luxury Hub",
    sellerRating: 4.6,
    reviewCount: 67,
    createdAt: "2024-08-05",
    type: "buy",
    colors: ["Rosso Corsa", "Blu Pozzi"],
    inventory: 1,
  },
  {
    id: "5",
    slug: "f40-heritage",
    title: "F40 Heritage",
    description: "Collector-grade icon, pristine condition.",
    price: 1400000,
    priceNegotiable: false,
    category: "classic",
    subcategory: "Vintage",
    images: ["/carousel6.png"],
    city: "London",
    university: "Imperial",
    userName: "Collectors",
    sellerRating: 5,
    reviewCount: 24,
    createdAt: "2024-07-01",
    type: "buy",
    colors: ["Rosso Corsa"],
    inventory: 1,
  },
  {
    id: "6",
    slug: "challenge-evo",
    title: "488 Challenge Evo",
    description: "Factory race car with full telemetry package.",
    price: 520000,
    priceNegotiable: true,
    category: "race",
    subcategory: "Challenge",
    images: ["/carousel8.webp"],
    city: "Barcelona",
    university: "UB",
    userName: "Track Pro",
    sellerRating: 4.5,
    reviewCount: 41,
    createdAt: "2024-06-12",
    type: "both",
    colors: ["Rosso Scuderia", "Bianco Avus"],
    inventory: 2,
  },
  {
    id: "7",
    slug: "merch-kit",
    title: "Team Merch Kit",
    description: "Apparel bundle from the latest season.",
    price: 680,
    priceNegotiable: true,
    category: "merch",
    subcategory: "Apparel",
    images: ["/carousel9.webp"],
    city: "Milan",
    university: "Polimi",
    userName: "Store",
    sellerRating: 4.4,
    reviewCount: 18,
    createdAt: "2024-05-25",
    type: "buy",
    colors: ["Rosso Corsa", "Nero"],
    inventory: 10,
  },
];

